version: '3'
services:
  nodejs-server:
    image: oreynaldocl/ang-node-api:latest
    ports:
      - "3080:3080"
    container_name: node-api
  angular-ui:
    image: oreynaldocl/ang-node-ui:latest
    ports:
      - "4201:80"
    container_name: angular-ui
    depends_on:
      - node-api
