apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  selector:
    app: backend-api
  type: ClusterIP # Only internal communication
  ports:
  - protocol: 'TCP'
    port: 3080
    targetPort: 3080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api-container
          image: oreynaldocl/ang-node-api:latest
