FROM node:10-alpine

WORKDIR /usr/src/app

COPY package*.json ./

#RUN npm install
# If you are building your code for production
RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 3080
CMD [ "node", "server.js" ]
